### ISSUE TITLE
Build issue on OpenBSD -current

### ISSUE THREAD

**Issue by 0x6a73** [ofek/coincurve#48] opened 2019-08-09 16:23 UTC
Hello. Currently, it's not possible to install coincurve using pip3.7 on an OpenBSD(on -current branch) system with bitcoin-0.18.0 (includes the latest libsecp256k1 with enabled ECDH module) installed. It's worth to note that I had to add `CFLAGS="-I/usr/local/include"` in order to make it detect header files. After running `pip3.7 install --user coincurve`, I get the following output:
```

Collecting coincurve
  Using cached https://files.pythonhosted.org/packages/4f/4b/c1c0aaa3a09d21e08de158f25e69134ea4b6563a8d5aee8d99e5f3e3447b/coincurve-12.0.0.tar.gz
Requirement already satisfied: asn1crypto in /home/ur_0x6a73/.local/lib/python3.7/site-packages (from coincurve)
Requirement already satisfied: cffi>=1.3.0 in /home/ur_0x6a73/.local/lib/python3.7/site-packages (from coincurve)
Requirement already satisfied: pycparser in /home/ur_0x6a73/.local/lib/python3.7/site-packages (from cffi>=1.3.0->coincurve)
Installing collected packages: coincurve
  Running setup.py install for coincurve: started
    Running setup.py install for coincurve: finished with status 'error'
    Complete output from command /usr/local/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-rh26wf9v/coincurve/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-e41ufrxj-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    Warning: 'keywords' should be a list, got type 'tuple'
    running install
    running build
    running build_py
    creating build
    creating build/lib.openbsd-6.5-amd64-3.7
    creating build/lib.openbsd-6.5-amd64-3.7/coincurve
    copying coincurve/_windows_libsecp256k1.py -> build/lib.openbsd-6.5-amd64-3.7/coincurve
    copying coincurve/flags.py -> build/lib.openbsd-6.5-amd64-3.7/coincurve
    copying coincurve/context.py -> build/lib.openbsd-6.5-amd64-3.7/coincurve
    copying coincurve/ecdsa.py -> build/lib.openbsd-6.5-amd64-3.7/coincurve
    copying coincurve/utils.py -> build/lib.openbsd-6.5-amd64-3.7/coincurve
    copying coincurve/keys.py -> build/lib.openbsd-6.5-amd64-3.7/coincurve
    copying coincurve/__init__.py -> build/lib.openbsd-6.5-amd64-3.7/coincurve
    running build_ext
    generating cffi module 'build/temp.openbsd-6.5-amd64-3.7/_libsecp256k1.c'
    creating build/temp.openbsd-6.5-amd64-3.7
    building '_libsecp256k1' extension
    creating build/temp.openbsd-6.5-amd64-3.7/build
    creating build/temp.openbsd-6.5-amd64-3.7/build/temp.openbsd-6.5-amd64-3.7
    cc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fPIC -O2 -pipe -O2 -pipe -I/usr/local/include -fPIC -I/usr/local/include/python3.7m -c build/temp.openbsd-6.5-amd64-3.7/_libsecp256k1.c -o build/temp.openbsd-6.5-amd64-3.7/build/temp.openbsd-6.5-amd64-3.7/_libsecp256k1.o
    build/temp.openbsd-6.5-amd64-3.7/_libsecp256k1.c:1578:41: error: too many arguments to function call, expected 4, have 6
      return secp256k1_ecdh(x0, x1, x2, x3, x4, x5);
             ~~~~~~~~~~~~~~                 ^~~~~~
    /usr/local/include/secp256k1_ecdh.h:20:15: note: 'secp256k1_ecdh' declared here
    SECP256K1_API SECP256K1_WARN_UNUSED_RESULT int secp256k1_ecdh(
                  ^
    /usr/local/include/secp256k1.h:134:40: note: expanded from macro 'SECP256K1_WARN_UNUSED_RESULT'
    #  define SECP256K1_WARN_UNUSED_RESULT __attribute__ ((__warn_unused_result__))
                                           ^
    build/temp.openbsd-6.5-amd64-3.7/_libsecp256k1.c:1670:45: error: too many arguments to function call, expected 4, have 6
      { result = secp256k1_ecdh(x0, x1, x2, x3, x4, x5); }
                 ~~~~~~~~~~~~~~                 ^~~~~~
    /usr/local/include/secp256k1_ecdh.h:20:15: note: 'secp256k1_ecdh' declared here
    SECP256K1_API SECP256K1_WARN_UNUSED_RESULT int secp256k1_ecdh(
                  ^
    /usr/local/include/secp256k1.h:134:40: note: expanded from macro 'SECP256K1_WARN_UNUSED_RESULT'
    #  define SECP256K1_WARN_UNUSED_RESULT __attribute__ ((__warn_unused_result__))
                                           ^
    2 errors generated.
    error: command 'cc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-rh26wf9v/coincurve/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-e41ufrxj-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-rh26wf9v/coincurve/
You are using pip version 9.0.3, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by leycec** [comment] 2019-10-01 07:32
**Gentoo here.** We're drunkenly stumbling over the same exact issue.

For safety, fetching arbitrary tarballs is prohibited during package installation on Gentoo; instead, we leverage the existing system-wide `libsecp256k1` library as a mandatory package dependency installed in a sane manner by our package manager, Portage. *So far so good.*

Unfortunately, `coincurve` appears to expect a non-standard `libsecp256k1` installation. Which version of `libsecp256k1` exactly does the most recent stable release of `coincurve` (i.e., 12.0.0 as of this writing) require? We've iteratively tried all of the available versions under Gentoo – to utterly no avail.

I note the cray-cray URL https://github.com/bitcoin-core/secp256k1/archive/b19c000063be11018b4d1a6b0a85871ab9d0bdcf.tar.gz in `setup.py`, but have no idea which version of `libsecp256k1` that actually corresponds to. I even went so far so to manually fetch and unpack that tarball. Insanely, grepping for a version string within that tarball yields... **absolutely nothing.** Yep! The tarball isn't even versioned. *What is going on here, I don't even.*

Help us, @ofek, for we are trying to help you by packaging you.

**Comment by leycec** [comment] 2019-10-01 07:37
**Oh, bloody feckballs.** `coincurve` requires an *extremely* recent version of `libsecp256k1`. Specifically, `coincurve` requires a `libsecp256k1` commit at least as recent as [commit b19c000063be11018b4d1a6b0a85871ab9d0bdcf](https://github.com/bitcoin-core/secp256k1/commit/b19c000063be11018b4d1a6b0a85871ab9d0bdcf) from March 31st of this year.

You know... it'd be useful to document non-trivial details about core mandatory dependencies like this if you want Linux distributions to voluntarily package your work. *Just sayin'.*

Well, at least I know why nobody ever packaged `coincurve` before. `</mournful_sigh>`

**Comment by ofek** [comment] 2019-10-01 13:15
@0x6a73 @leycec Hello there! I very much appreciate your willingness to package this library.

Based on your error and https://github.com/ofek/coincurve/pull/33, it looks like the issue is you'll need a version that includes the breaking ECDH change https://github.com/bitcoin-core/secp256k1/commit/c8fbc3c397b547bc64435a9bffb8f989cd23aba0.

**Comment by leycec** [comment] 2019-10-02 01:27
**Awesomeness.** Thanks for all the intrepid open-sourcery and prompt reply, @ofek. I was *just* in the laborious process of authoring an updated `dev-libs/libsecp256k1` ebuild satisfying `dev-python/coincurve` requirements. And how absurd is it that `libsecp256k1` has yet to package a single stable release despite nearly a decade's worth of commits? <sup>*"Very absurd" is my answer.*</sup>

For parity with your `setup.py` build chain, we'll probably go with the more recent [commit b19c000063be11018b4d1a6b0a85871ab9d0bdcf](https://github.com/bitcoin-core/secp256k1/commit/b19c000063be11018b4d1a6b0a85871ab9d0bdcf) rather than the comparatively older [commit c8fbc3c397b547bc64435a9bffb8f989cd23aba0](https://github.com/bitcoin-core/secp256k1/commit/c8fbc3c397b547bc64435a9bffb8f989cd23aba0). Welp, let's give that a spin and see how many errors `gcc` vomits up now.

Muchas gracias, again. Your username shall be praised in legend and song.

**Comment by ofek** [comment] 2019-10-02 02:22
@leycec Ah I'm glad you're doing this, it makes me very happy! Yeah breaking changes aren't fun haha. Hey, would you mind linking some docs on the Gentoo packaging process? I'm quite intrigued.

@0x6a73 Are you also attempting to package?

**Comment by leycec** [comment] 2019-10-03 05:20
**Blammo!** [Gentoo ebuilds for `coincurve` are now live](https://github.com/leycec/raiagent/tree/master/dev-python/coincurve).

Incidentally, you might be curious as to why everybody is suddenly interested in packaging `coincurve`. Let us now reveal the truth:

1. `coincurve` is awesome, so obviously everybody would want to package it. (*This is true.*)
1. `coincurve` is now a mandatory dependency of [ZeroNet >= 0.7.0](https://github.com/HelloZeroNet/ZeroNet) – teh best and probably only Python-based darknet. (*This is also true.*)

One of those two reasons might be more relevant.

> Hey, would you mind linking some docs on the Gentoo packaging process? 

[*One does not simply package for Gentoo.*](https://wiki.gentoo.org/wiki/Basic_guide_to_write_Gentoo_Ebuilds)

Seriously, though; the Gentoo packaging process is a dismal thing cobbled together with mouldy ducktape and rancid glue. If I hadn't see how other package managers package, I wouldn't recommend it. But I *have* seen how other package managers package – and they're all even worse! Much, much worse.

Especially Debian. Oh, lordy. Debian packaging is inscrutable, obfuscatory, and bureaucratic to the hilt. (Much like Canonical. *What a surprise.*)

If you'd still like to package for Gentoo... welcome! There are at least twelve of us. Together, we keep the flames of source-based Linux packaging still lit. As with most endeavours in life, the best way to learn it... *is to just do it.* Right? Learn by doing >>>> learn by reading.

Thankfully, "just do it" ain't that tough. It's more a matter of time and patience than skill and talent. The barrier to entry is much lower for Gentoo than it is for more heavyweight Linux distributions – probably because we're desperate for fresh ~~blood~~ volunteers. We try to make the hard things less hard and the easy things more easy.

Perusing the [`coincurve` ebuilds I just authored](https://github.com/leycec/raiagent/tree/master/dev-python/coincurve) might be a useful place to start. Assuming you like what you see <sup>*...you probably won't*</sup> and actually have a working Gentoo system <sup>*...you probably don't*</sup>, consider submitting pull requests to bump those `coincurve` ebuilds whenever you publish a new stable release.

But, yeah... ain't no one got time for that. Pretending that Gentoo packaging doesn't exist might be the sanest policy. Your volunteer resources are probably better spent elsewhere. Like, *anywhere.*

Thanks again for all the curvy coins, @ofek. Californian palm trees for all! :palm_tree: :palm_tree: :palm_tree:

**Comment by 0x6a73** [comment] 2019-10-03 18:29
@ofek Thanks for replying. No, I've found out that someone just started working on it. It seems like he's got it working, I think.

**Comment by ofek** [comment] 2019-10-03 19:00
Both of you are 🥇 

@0x6a73 Whenever you confirm it works, feel free to close this out!

**Comment by 0x6a73** [comment] 2019-10-04 17:04
Oh, sorry. I've just checked out the mailing list archives and it was an other Bitcoin cryptography related python library with the exact same problem. It seems like coincurve needs a few more OpenBSD-specific tweaks. I'll try to make a pull request with required changes in a few minutes.

**Comment by ofek** [comment] 2019-10-04 17:08
@0x6a73 Great, thanks!

**Comment by 0x6a73** [comment] 2019-10-04 17:18
Yep, just changing a single line of code was enough to get it working. I'm making a pull request now. Also, it seems like the automake stage needs some env variables to be present such as AUTOMAKE_VERSION and AUTOCONF_VERSION, but these are not usually available by default, so if you don't mind I'll add a small disclaimer about installing on OpenBSD in the README file. Most ports packages automatically add then while building though AFAIK, so it's only for manual builds.

**Comment by ofek** [comment] 2019-10-06 02:05
Resolved via https://github.com/ofek/coincurve/pull/51 😄

**Closed by ofek** 2019-10-06 02:05 UTC
