### ISSUE TITLE
19.0.0 yanked?

### ISSUE THREAD

**Issue by hhartzer** [ofek/coincurve#144] opened 2024-02-04 17:00 UTC
It looks like 19.0.0 was yanked from pypi. Was there an important issue that caused this? Will there be a 20.0.0 or 19.0.1 soon?

Thank you!

**Comment by darosior** [comment] 2024-02-22 15:40
See https://github.com/ofek/coincurve/issues/133

**Comment by MementoRC** [comment] 2024-02-22 16:21
Would you be able to test `master`? A PR, which should resolve this issue was merged a few weeks ago. Also, if you happen to be running within conda, the conda version should not exhibit this issue

**Comment by hhartzer** [comment] 2024-02-26 23:45
@darosior I think this is for you

**Comment by darosior** [comment] 2024-02-27 09:02
No i think it's for you. Memento knows i don't use Conda since that's how i came up with the issue in the first place.

-------- Original Message --------

**Comment by MementoRC** [comment] 2024-02-27 14:56
The key point was more on trying to use `coincurve:master` just to confirm that the issue is resolved.
conda was more of a general advertisement for anyone stumbling on this thread

**Comment by darosior** [comment] 2024-02-27 15:00
Alright i'll update the python-bip32 PR to temporarily use coincure:master to see if it solves the issue.

**Comment by ofek** [comment] 2024-03-02 17:43
Fixed: https://github.com/ofek/coincurve/releases/tag/v19.0.1

**Closed by ofek** 2024-03-02 17:43 UTC
