### ISSUE TITLE
Import fails on macOS 12 arm64 with Python 3.10

### ISSUE THREAD

**Issue by robd003** [ofek/coincurve#108] opened 2021-12-19 23:25 UTC
For some reason python claims it can't find the function **_secp256k1_nonce_function_default** in the coincurve/_libsecp256k1.cpython-310-darwin.so library... However a dump from nm shows that it's available.

Error from python:
```
Python 3.10.1 (main, Dec  6 2021, 22:18:13) [Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import coincurve
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/robd/code/lbry-sdk/env/lib/python3.10/site-packages/coincurve-16.0.0-py3.10-macosx-12-arm64.egg/coincurve/__init__.py", line 1, in <module>
    from coincurve.context import GLOBAL_CONTEXT, Context
  File "/Users/robd/code/lbry-sdk/env/lib/python3.10/site-packages/coincurve-16.0.0-py3.10-macosx-12-arm64.egg/coincurve/context.py", line 4, in <module>
    from coincurve.flags import CONTEXT_ALL, CONTEXT_FLAGS
  File "/Users/robd/code/lbry-sdk/env/lib/python3.10/site-packages/coincurve-16.0.0-py3.10-macosx-12-arm64.egg/coincurve/flags.py", line 1, in <module>
    from ._libsecp256k1 import lib
ImportError: dlopen(/Users/robd/code/lbry-sdk/env/lib/python3.10/site-packages/coincurve-16.0.0-py3.10-macosx-12-arm64.egg/coincurve/_libsecp256k1.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_secp256k1_nonce_function_default'
```

nm dump of coincurve/_libsecp256k1.cpython-310-darwin.so:
```
                 U _PyArg_UnpackTuple
                 U _PyErr_Occurred
                 U _PyEval_RestoreThread
                 U _PyEval_SaveThread
                 U _PyImport_ImportModule
0000000000001998 T _PyInit__libsecp256k1
                 U _PyLong_FromLong
                 U _PyLong_FromVoidPtr
                 U _PyObject_CallMethod
                 U _PyObject_Free
                 U _PyObject_Malloc
                 U __Py_Dealloc
                 U __Py_NoneStruct
                 U ___chkstk_darwin
                 U ___stack_chk_fail
                 U ___stack_chk_guard
                 U _bzero
                 U _secp256k1_context_clone
                 U _secp256k1_context_create
                 U _secp256k1_context_destroy
                 U _secp256k1_context_randomize
                 U _secp256k1_context_set_error_callback
                 U _secp256k1_context_set_illegal_callback
                 U _secp256k1_ec_privkey_tweak_add
                 U _secp256k1_ec_privkey_tweak_mul
                 U _secp256k1_ec_pubkey_combine
                 U _secp256k1_ec_pubkey_create
                 U _secp256k1_ec_pubkey_parse
                 U _secp256k1_ec_pubkey_serialize
                 U _secp256k1_ec_pubkey_tweak_add
                 U _secp256k1_ec_pubkey_tweak_mul
                 U _secp256k1_ec_seckey_verify
                 U _secp256k1_ecdh
                 U _secp256k1_ecdsa_recover
                 U _secp256k1_ecdsa_recoverable_signature_convert
                 U _secp256k1_ecdsa_recoverable_signature_parse_compact
                 U _secp256k1_ecdsa_recoverable_signature_serialize_compact
                 U _secp256k1_ecdsa_sign
                 U _secp256k1_ecdsa_sign_recoverable
                 U _secp256k1_ecdsa_signature_normalize
                 U _secp256k1_ecdsa_signature_parse_compact
                 U _secp256k1_ecdsa_signature_parse_der
                 U _secp256k1_ecdsa_signature_serialize_compact
                 U _secp256k1_ecdsa_signature_serialize_der
                 U _secp256k1_ecdsa_verify
                 U _secp256k1_nonce_function_default
                 U _secp256k1_nonce_function_rfc6979
                 U dyld_stub_binder
```

If anyone could help me figure out **why** python can't find a function that's plainly available (3rd from the bottom of the list right above) I'd love to know how to fix this.

**Comment by robd003** [comment] 2021-12-19 23:56
Manually trying to load the _libsecp256k1 library returns this error:

```
from CFFI import FFI
FFI().dload("/Users/robd/code/lbry-sdk/env/lib/python3.10/site-packages/coincurve-16.0.0-py3.10-macosx-12-arm64.egg/coincurve/_libsecp256k1.cpython-310-darwin.so")

OSError: cannot load library '/Users/robd/code/lbry-sdk/env/lib/python3.10/site-packages/coincurve-16.0.0-py3.10-macosx-12-arm64.egg/coincurve/_libsecp256k1.cpython-310-darwin.so': dlopen(/Users/robd/code/lbry-sdk/env/lib/python3.10/site-packages/coincurve-16.0.0-py3.10-macosx-12-arm64.egg/coincurve/_libsecp256k1.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_secp256k1_nonce_function_default'.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/Users/robd/code/lbry-sdk/env/lib/python3.10/site-packages/coincurve-16.0.0-py3.10-macosx-12-arm64.egg/coincurve/_libsecp256k1.cpython-310-darwin.so'
```

**Comment by robd003** [comment] 2021-12-21 16:34
@ofek any chance you know whats going on here?

**Comment by ofek** [comment] 2021-12-21 17:09
Did you build from source?

**Comment by robd003** [comment] 2021-12-22 00:26
@ofek Yes

**Comment by robd003** [comment] 2021-12-22 00:39
This was from installing from the macOS Python 3.10 arm64 wheel.

Interestingly when building from source this is the results from nm on the library:

```
nm -g coincurve/_libsecp256k1.cpython-310-darwin.so 
                 U _PyArg_UnpackTuple
                 U _PyErr_Occurred
                 U _PyEval_RestoreThread
                 U _PyEval_SaveThread
                 U _PyImport_ImportModule
00000000000017c0 T _PyInit__libsecp256k1
                 U _PyLong_FromLong
                 U _PyLong_FromVoidPtr
                 U _PyObject_CallMethod
                 U _PyObject_Free
                 U _PyObject_Malloc
                 U __Py_Dealloc
                 U __Py_NoneStruct
                 U ___chkstk_darwin
                 U ___gmpn_gcdext
                 U ___gmpn_get_str
                 U ___gmpn_set_str
                 U ___gmpn_sub_n
                 U ___stack_chk_fail
                 U ___stack_chk_guard
                 U ___stderrp
                 U _abort
                 U _bzero
                 U _fprintf
                 U _free
                 U _malloc
                 U _memcpy
0000000000007614 T _secp256k1_context_clone
000000000000751c T _secp256k1_context_create
0000000000007724 T _secp256k1_context_destroy
00000000000304d0 D _secp256k1_context_no_precomp
000000000000758c T _secp256k1_context_preallocated_clone
0000000000007304 T _secp256k1_context_preallocated_clone_size
0000000000007320 T _secp256k1_context_preallocated_create
00000000000076c0 T _secp256k1_context_preallocated_destroy
00000000000072d4 T _secp256k1_context_preallocated_size
000000000000b44c T _secp256k1_context_randomize
0000000000007804 T _secp256k1_context_set_error_callback
0000000000007770 T _secp256k1_context_set_illegal_callback
000000000000a9e4 T _secp256k1_ec_privkey_negate
000000000000ae24 T _secp256k1_ec_privkey_tweak_add
000000000000b24c T _secp256k1_ec_privkey_tweak_mul
000000000000bb40 T _secp256k1_ec_pubkey_combine
000000000000a670 T _secp256k1_ec_pubkey_create
000000000000a9e8 T _secp256k1_ec_pubkey_negate
000000000000798c T _secp256k1_ec_pubkey_parse
0000000000008008 T _secp256k1_ec_pubkey_serialize
000000000000ae28 T _secp256k1_ec_pubkey_tweak_add
000000000000b250 T _secp256k1_ec_pubkey_tweak_mul
000000000000a7d4 T _secp256k1_ec_seckey_negate
000000000000ab34 T _secp256k1_ec_seckey_tweak_add
000000000000b000 T _secp256k1_ec_seckey_tweak_mul
000000000000a5fc T _secp256k1_ec_seckey_verify
000000000000eb6c T _secp256k1_ecdh
000000000002c8a8 S _secp256k1_ecdh_hash_function_default
000000000002c8a0 S _secp256k1_ecdh_hash_function_sha256
0000000000010308 T _secp256k1_ecdsa_recover
00000000000101e8 T _secp256k1_ecdsa_recoverable_signature_convert
0000000000010040 T _secp256k1_ecdsa_recoverable_signature_parse_compact
0000000000010120 T _secp256k1_ecdsa_recoverable_signature_serialize_compact
0000000000009074 T _secp256k1_ecdsa_sign
0000000000010250 T _secp256k1_ecdsa_sign_recoverable
0000000000008a0c T _secp256k1_ecdsa_signature_normalize
00000000000085a4 T _secp256k1_ecdsa_signature_parse_compact
0000000000008434 T _secp256k1_ecdsa_signature_parse_der
0000000000008960 T _secp256k1_ecdsa_signature_serialize_compact
000000000000875c T _secp256k1_ecdsa_signature_serialize_der
0000000000008b68 T _secp256k1_ecdsa_verify
000000000002c898 S _secp256k1_nonce_function_default
000000000002c890 S _secp256k1_nonce_function_rfc6979
0000000000007898 T _secp256k1_scratch_space_create
000000000000790c T _secp256k1_scratch_space_destroy
```

**Comment by ofek** [comment] 2021-12-22 06:41
Oh, so building from source worked the second time?

**Comment by gitzhou** [comment] 2022-01-02 19:04
Python 3.8.9 on Mac 12.1 (21C52) got the same error

```
   from coincurve import PrivateKey, PublicKey
../venv/lib/python3.8/site-packages/coincurve/__init__.py:1: in <module>
    from coincurve.context import GLOBAL_CONTEXT, Context
../venv/lib/python3.8/site-packages/coincurve/context.py:4: in <module>
    from coincurve.flags import CONTEXT_ALL, CONTEXT_FLAGS
../venv/lib/python3.8/site-packages/coincurve/flags.py:1: in <module>
    from ._libsecp256k1 import lib
E   ImportError: dlopen(../venv/lib/python3.8/site-packages/coincurve/_libsecp256k1.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_secp256k1_nonce_function_default'
```

**Comment by ChristianOConnor** [comment] 2022-01-08 20:57
I've had the exact same problem. My terminal output is exactly the same as OP's. How do I fix this? I'm trying to use "ofek/bit" and I get the same error on coincurve. P.S. I have a 2021 MacBook M1 Pro.

**Comment by ofek** [comment] 2022-01-09 13:46
Can you try one of the macOS wheels in the artifacts at the bottom of this page? https://github.com/ofek/coincurve/actions/runs/1673052877

**Comment by gitzhou** [comment] 2022-01-09 15:02
Hi ofek, I did some personal tests.
When signing with coincurve, for message m1, it will use ephemeral private key k1 without changing, but for message m2, it will use k2. m1 ≠ m2 then k1 ≠ k2
fyi

**Comment by ChristianOConnor** [comment] 2022-01-09 23:17
> Can you try one of the macOS wheels in the artifacts at the bottom of this page? https://github.com/ofek/coincurve/actions/runs/1673052877

Still didn't work.  
  
I downloaded the "artifacts" zip from this link "https://github.com/ofek/coincurve/suites/4874293850/artifacts/139214397". It was on the page that you linked me.
  
I created a whole new virtualenv. Then I tried `pip install path/to/file/coincurve-16.0.0-cp310-cp310-macosx_11_0_arm64.whl` which worked, then I did `pip install bit` which also worked because the `coincurve` dependency was satisfied, but when I tried to run my app I still got this.  
  
```
(my_python_env) myusername@my_macbook_name gen_aspen % python main.py 
Traceback (most recent call last):
  File "/Users/myusername/Desktop/Dev/ScratchSpace/genAspenCustomBitWheel/gen_aspen/main.py", line 5, in <module>
    import create_btc
  File "/Users/myusername/Desktop/Dev/ScratchSpace/genAspenCustomBitWheel/gen_aspen/create_btc.py", line 1, in <module>
    from bit import PrivateKeyTestnet
  File "/Users/myusername/.virtualenvs/my_python_env/lib/python3.10/site-packages/bit/__init__.py", line 1, in <module>
    from bit.format import verify_sig
  File "/Users/myusername/.virtualenvs/my_python_env/lib/python3.10/site-packages/bit/format.py", line 1, in <module>
    from coincurve import verify_signature as _vs
  File "/Users/myusername/.virtualenvs/my_python_env/lib/python3.10/site-packages/coincurve/__init__.py", line 1, in <module>
    from coincurve.context import GLOBAL_CONTEXT, Context
  File "/Users/myusername/.virtualenvs/my_python_env/lib/python3.10/site-packages/coincurve/context.py", line 4, in <module>
    from coincurve.flags import CONTEXT_ALL, CONTEXT_FLAGS
  File "/Users/myusername/.virtualenvs/my_python_env/lib/python3.10/site-packages/coincurve/flags.py", line 1, in <module>
    from ._libsecp256k1 import lib
ImportError: dlopen(/Users/myusername/.virtualenvs/my_python_env/lib/python3.10/site-packages/coincurve/_libsecp256k1.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_secp256k1_nonce_function_default'
```  
  
What do you think the problem is? @ofek

**Comment by dwjorgeb** [comment] 2022-01-28 20:40
did you manage to fix for this issue? I'm having the same issue @ChristianOConnor

**Comment by ChristianOConnor** [comment] 2022-01-28 21:27
I had to use a much older version of python (I think I went with python 3.7) and an older version of coincurve. I think I used coincurve 13 with `pip install coincurve==13.0.0`. The older versions of coincurve don't use `libsecp256k1` which seems to not work on M1 macs.

**Comment by ofek** [comment] 2022-01-29 18:18
I think I fixed the cross-compiling. Can you try? https://github.com/ofek/coincurve/suites/5108282013/artifacts/153027466

**Comment by robd003** [comment] 2022-01-29 22:27
> I think I fixed the cross-compiling. Can you try? https://github.com/ofek/coincurve/suites/5108282013/artifacts/153027466

Taking a look now @ofek

**Comment by robd003** [comment] 2022-01-29 22:31
@ofek I was able to load and import coincurve-16.0.0-cp310-cp310-macosx_11_0_arm64.whl just fine on macOS 12 and Python 3.10

Can you push these wheels to PyPi?

**Comment by ofek** [comment] 2022-01-30 05:47
Fixed! https://pypi.org/project/coincurve/17.0.0/

**Closed by ofek** 2022-01-30 05:47 UTC

**Comment by robd003** [comment] 2022-01-30 14:02
Thanks @ofek you rock!

**Comment by vhscom** [comment] 2023-11-04 05:08
> I had to use a much older version of python (I think I went with python 3.7) and an older version of coincurve. I think I used coincurve 13 with `pip install coincurve==13.0.0`. The older versions of coincurve don't use `libsecp256k1` which seems to not work on M1 macs.

I can confirm this works on the M2 chipset using the exact versions specified. Ran into this trying to build ZeroNet under Fedora Asahi Linux.

**Comment by vhscom** [comment] 2023-11-04 05:08
> I had to use a much older version of python (I think I went with python 3.7) and an older version of coincurve. I think I used coincurve 13 with `pip install coincurve==13.0.0`. The older versions of coincurve don't use `libsecp256k1` which seems to not work on M1 macs.

I can confirm this works on the M2 chipset using the exact versions specified. Ran into this building ZeroNet under Fedora Asahi Linux.

**Comment by vhscom** [comment] 2023-11-04 05:10
> I had to use a much older version of python (I think I went with python 3.7) and an older version of coincurve. I think I used coincurve 13 with `pip install coincurve==13.0.0`. The older versions of coincurve don't use `libsecp256k1` which seems to not work on M1 macs.

I can confirm this works on the M2 chipset using the exact versions specified. Saw building ZeroNet under Fedora Asahi Remix.

**Comment by vhscom** [comment] 2023-11-04 05:11
> I had to use a much older version of python (I think I went with python 3.7) and an older version of coincurve. I think I used coincurve 13 with `pip install coincurve==13.0.0`. The older versions of coincurve don't use `libsecp256k1` which seems to not work on M1 macs.

I can confirm this works on the M2 chipset using the exact versions specified. Saw building ZeroNet under Asahi Linux.
